config:
    connection:
          socket:
#              host: 192.168.137.45
              host: 127.0.0.1
              port: 5000
          drone:
              host: 0.0.0.0
              port: 14551
