config:
    connection:
          socket:
              host: localhost
#              host: 148.60.13.10
              port: 8082
          drone:
              host: 0.0.0.0
              port: 14551
